name: Functional Unit Tests
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  Functional_Unit_Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Google Test
        run: apt install libgtest-dev libgmock-dev
      - name: Build
        working-directory: ${{github.workspace}}
        run: make debug
      - name: Run Test
        working-directory: ${{github.workspace}}
        run: make test
